#146 - Set default log level for non-prod environment to DEBUG
department-of-veterans-affairs/notification-utils pull request #155
Opened 2024-06-24 14:23 UTC by MackHalliday

2024-06-26 03:06 UTC, MackHalliday commented on scripts/run_tests.sh
> +# display_result $? 1 "Code style check"
Temporarily comment out

2024-06-26 03:28 UTC, MackHalliday commented on notifications_utils/logging.py
> +    print("This is the log level", loglevel)
This does not seem to show up in logs when running locally in Docker

2024-06-27 18:24 UTC, MackHalliday commented on notifications_utils/logging.py
>  import logging
pep8 sort

2024-06-27 18:25 UTC, MackHalliday commented on notifications_utils/logging.py
> +def set_log_level(app):
logic to set log level

2024-06-27 18:27 UTC, MackHalliday commented on tests/test_logging.py
> +class App:
Create shared test resources

2024-06-27 18:27 UTC, MackHalliday commented on tests/test_logging.py
> +def test_it_set_log_level_production(app, reset_environment):
Tests for setting log level

2024-06-27 18:59 UTC, kalbfled requested changes

2024-06-27 18:59 UTC, kalbfled commented on notifications_utils/logging.py
> +    # For all other environment, set log level to DEBUG
```suggestion
    """
    For production environment, set log level to INFO.
    For all other environment, set log level to DEBUG.
    """
```

2024-06-27 19:04 UTC, kalbfled approved these changes

2024-06-27 19:36 UTC, k-macmillan approved these changes

2024-06-27 19:43 UTC, merged